# frozen_string_literal: true
source "https://rubygems.org"

gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver'
gem 'faker'
gem 'poltergeist'
gem 'rspec'
gem 'ffi','1.9.14'
gem 'chromedriver-helper'